# Generated by Django 4.2.21 on 2025-05-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default-avatar.jpg', null=True, upload_to='avatar-upload/%Y/%m/%d/'),
        ),
    ]
