server {
    listen 80;
    server_name test.hieunamson.id.vn;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /python/store/static/;
    }
    location / {
        proxy_pass http://127.0.0.1:8000;
    }
}

