server {
    listen 80;
    server_name 103.157.204.128;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        alias /app/static/;
    }
    location / {
        proxy_pass http://web:8000;
    }
}

#server {
#    listen 80;
#    server_name 103.97.125.64:8000;

#    location = /favicon.ico { access_log off; log_not_found off; }
#    location /static/ {
#        alias /app/static/;
#    }
#    location / {
#        proxy_pass http://103.97.125.64:8000;
#    }
#}
