# Generated by Django 4.2.21 on 2025-05-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
