# Generated by Django 4.2.21 on 2025-05-23 15:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image', models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='product_image_upload/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
