# Generated by Django 4.2.21 on 2025-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage_remove_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='product_thumbnail_upload/%Y/%m/%d/'),
        ),
    ]
