# Generated by Django 4.2.21 on 2025-05-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default_product_thumbnail.png', null=True, upload_to='product_thumbnail_upload/%Y/%m/%d/'),
        ),
    ]
