# Generated by Django 4.2.21 on 2025-05-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='default/default_product_thumbnail.png', null=True, upload_to='product_image_upload/%Y/%m/%d/'),
        ),
    ]
