# Generated by Django 4.2.21 on 2025-05-30 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='account_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
