# Generated by Django 4.2.21 on 2025-05-31 07:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_feedback_account_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_uuid', models.UUIDField(default=uuid.uuid4)),
                ('thumbnail', models.ImageField(blank=True, default='default/default_product_thumbnail.png', null=True, upload_to='product_thumbnail_upload/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
    ]
