# Generated by Django 4.2.21 on 2025-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productthumbnail_remove_productimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image_upload/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productthumbnail',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_thumbnail_upload/%Y/%m/%d/'),
        ),
    ]
