# Generated by Django 4.2.21 on 2025-06-28 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
