# Generated by Django 4.2.21 on 2025-06-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_categories_name'),
        ('product', '0011_alter_feedback_order_uuid'),
    ]

    operations = [
    ]
