"""
Django settings for LawChatbot project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from os import environ
# from dotenv import load_dotenv
# from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(dotenv_path=BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hlpl(tt6ph+!$4^=1phb3)2b-fd97q()5q=5#mwii*!mr^*3h3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "http://hieunamson.id.vn",
    "https://hieunamson.id.vn",  # nếu bạn dùng HTTPS 
    "http://test.hieunamson.id.vn",
    "https://test.hieunamson.id.vn",  # nếu bạn dùng HTTPS
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'rest_framework',
    # "debug_toolbar",
    # "channels",
    # "law_data_prepare",
  
]

MY_APPS = []
from .app_list import APP_LIST

for app in APP_LIST:
    MY_APPS.append(app)

INSTALLED_APPS.extend(MY_APPS)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # "debug_toolbar.middleware.DebugToolbarMiddleware",

]

ROOT_URLCONF = 'store.urls'

TEMPLATE_DIRS = [
    os.path.join(BASE_DIR, 'store', 'templates'),  # Absolute Path
    os.path.join(BASE_DIR, 'portal', 'templates'),  # Absolute Path
    # os.path.join(BASE_DIR, 'workspace', 'templates'),  # Absolute Path
]

for app in APP_LIST:
    TEMPLATE_DIRS.append(os.path.join(BASE_DIR, app, 'templates'))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

NS_store_DB_HOST = "localhost"
if environ.get('NS_store_DB_HOST') is not None:
    NS_store_DB_HOST = environ.get('NS_store_DB_HOST')

NS_store_DB_PORT = "5432"
if environ.get('NS_store_DB_PORT') is not None:
    NS_store_DB_PORT = environ.get('NS_store_DB_PORT')

NS_store_DB_NAME = "store"
if environ.get('NS_store_DB_NAME') is not None:
    NS_store_DB_NAME = environ.get('NS_store_DB_NAME')

NS_store_DB_SCHEMA = "public"
if environ.get('NS_store_DB_SCHEMA') is not None:
    NS_store_DB_SCHEMA = environ.get('NS_store_DB_SCHEMA')

NS_store_DB_USER = "postgres"
if environ.get('NS_store_DB_USER') is not None:
    NS_store_DB_USER = environ.get('NS_store_DB_USER')

NS_store_DB_PASSWORD = "123456"
if environ.get('NS_store_DB_PASSWORD') is not None:
    NS_store_DB_PASSWORD = environ.get('NS_store_DB_PASSWORD')

NS_store_DB_TEST_HOST = "localhost"
if environ.get('NS_store_DB_TEST_HOST') is not None:
    NS_store_DB_TEST_HOST = environ.get('NS_store_DB_TEST_HOST')

NS_store_DB_TEST_PORT = "5432"
if environ.get('NS_store_DB_TEST_PORT') is not None:
    NS_store_DB_TEST_PORT = environ.get('NS_store_DB_TEST_PORT')

NS_store_DB_TEST_NAME = "testdb_manager"
if environ.get('NS_store_DB_TEST_NAME') is not None:
    NS_store_DB_TEST_NAME = environ.get('NS_store_DB_TEST_NAME')

NS_store_DB_TEST_SCHEMA = "public"
if environ.get('NS_store_DB_TEST_SCHEMA') is not None:
    NS_store_DB_TEST_SCHEMA = environ.get('NS_store_DB_TEST_SCHEMA')

NS_store_DB_TEST_USER = "thong"
if environ.get('NS_store_DB_TEST_USER') is not None:
    NS_store_DB_TEST_USER = environ.get('NS_store_DB_TEST_USER')

NS_store_DB_TEST_PASSWORD = "1"
if environ.get('NS_store_DB_TEST_PASSWORD') is not None:
    NS_store_DB_TEST_PASSWORD = environ.get('NS_store_DB_TEST_PASSWORD')

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'ENGINE': 'psqlextra.backend',
        'OPTIONS': {
            'options': str('-c search_path=%s,public' % NS_store_DB_SCHEMA)
        },
        'NAME': NS_store_DB_NAME,
        'USER': NS_store_DB_USER,
        'PASSWORD': NS_store_DB_PASSWORD,
        'HOST': 'db',
        # 'HOST': NS_store_DB_HOST,
        'PORT': NS_store_DB_PORT,
        'TEST': {
            'NAME': NS_store_DB_TEST_NAME,
            'USER': NS_store_DB_TEST_USER,
            'PASSWORD': NS_store_DB_TEST_PASSWORD,
            'HOST': NS_store_DB_TEST_HOST,
            'PORT': NS_store_DB_TEST_PORT,
            'SCHEMA': "test",
            # 'OPTIONS': {
            #     'options': str('-c search_path=%s' % "test")
            # },
        }
    },
}

# REDIS_CACHE_HOST = '127.0.0.1'
# REDIS_CACHE_PORT = 6379
# REDIS_CACHE_PASSWORD = '123456'
# REDIS_CACHE_DB = 6
# # REDIS CACHES
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": f"redis://:{REDIS_CACHE_PASSWORD}@{REDIS_CACHE_HOST}:{REDIS_CACHE_PORT}/{REDIS_CACHE_DB}",  # 0-15
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "SERIALIZER": "django_redis.serializers.pickle.PickleSerializer",
#             "PASSWORD": "123456",
#         }
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'store', 'static'),  # Absolute Path
    os.path.join(BASE_DIR, 'portal', 'static'),  # Absolute Path
]

for app in APP_LIST:
    STATICFILES_DIRS.append(os.path.join(BASE_DIR, app, 'static'))

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "account.Account"

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # test
SITE_ID = 1
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "your-email@gmail.com"
EMAIL_HOST_PASSWORD = "your-email-password"

ASGI_APPLICATION = "store.asgi.application"

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("localhost", 6379)],
#         },
#     },
# }
