# Generated by Django 4.2.21 on 2025-05-23 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
