# Generated by Django 4.2.21 on 2025-05-24 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_account_uuid_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
