# Generated by Django 4.2.21 on 2025-05-27 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_shipping_price_alter_orderitem_order_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='order',
            name='account_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
